// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/auth.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_v1_auth_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "options.v1.no_auth",
		Tag:           "varint,50000,opt,name=no_auth",
		Filename:      "options/v1/auth.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "options.v1.admin_only",
		Tag:           "varint,50001,opt,name=admin_only",
		Filename:      "options/v1/auth.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "options.v1.reject_read_only",
		Tag:           "varint,50002,opt,name=reject_read_only",
		Filename:      "options/v1/auth.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "options.v1.service_no_auth",
		Tag:           "varint,50000,opt,name=service_no_auth",
		Filename:      "options/v1/auth.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "options.v1.service_admin_only",
		Tag:           "varint,50001,opt,name=service_admin_only",
		Filename:      "options/v1/auth.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Set no_auth = true on an RPC to bypass authentication.
	//
	// optional bool no_auth = 50000;
	E_NoAuth = &file_options_v1_auth_proto_extTypes[0]
	// Set admin_only = true on an RPC to restrict access to admin users.
	//
	// optional bool admin_only = 50001;
	E_AdminOnly = &file_options_v1_auth_proto_extTypes[1]
	// Set reject_read_only = true on an RPC to reject read-only users.
	//
	// optional bool reject_read_only = 50002;
	E_RejectReadOnly = &file_options_v1_auth_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Set service_no_auth = true to bypass authentication for all RPCs in a service.
	//
	// optional bool service_no_auth = 50000;
	E_ServiceNoAuth = &file_options_v1_auth_proto_extTypes[3]
	// Set service_admin_only = true to restrict all RPCs in a service to admin users.
	//
	// optional bool service_admin_only = 50001;
	E_ServiceAdminOnly = &file_options_v1_auth_proto_extTypes[4]
)

var File_options_v1_auth_proto protoreflect.FileDescriptor

const file_options_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x15options/v1/auth.proto\x12\n" +
	"options.v1\x1a google/protobuf/descriptor.proto:9\n" +
	"\ano_auth\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\bR\x06noAuth:?\n" +
	"\n" +
	"admin_only\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\tadminOnly:J\n" +
	"\x10reject_read_only\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\bR\x0erejectReadOnly:I\n" +
	"\x0fservice_no_auth\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\bR\rserviceNoAuth:O\n" +
	"\x12service_admin_only\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\bR\x10serviceAdminOnlyB<Z:github.com/jesse0michael/pkg/grpc/proto/options/v1;optionsb\x06proto3"

var file_options_v1_auth_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil),  // 0: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
}
var file_options_v1_auth_proto_depIdxs = []int32{
	0, // 0: options.v1.no_auth:extendee -> google.protobuf.MethodOptions
	0, // 1: options.v1.admin_only:extendee -> google.protobuf.MethodOptions
	0, // 2: options.v1.reject_read_only:extendee -> google.protobuf.MethodOptions
	1, // 3: options.v1.service_no_auth:extendee -> google.protobuf.ServiceOptions
	1, // 4: options.v1.service_admin_only:extendee -> google.protobuf.ServiceOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_v1_auth_proto_init() }
func file_options_v1_auth_proto_init() {
	if File_options_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_auth_proto_rawDesc), len(file_options_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_options_v1_auth_proto_goTypes,
		DependencyIndexes: file_options_v1_auth_proto_depIdxs,
		ExtensionInfos:    file_options_v1_auth_proto_extTypes,
	}.Build()
	File_options_v1_auth_proto = out.File
	file_options_v1_auth_proto_goTypes = nil
	file_options_v1_auth_proto_depIdxs = nil
}
