// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test.proto

package test

import (
	_ "github.com/jesse0michael/pkg/grpc/proto/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\ttestproto\x1a\x15options/v1/auth.proto\"\a\n" +
	"\x05Empty2\xe3\x01\n" +
	"\vTestService\x12.\n" +
	"\x06Authed\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x00\x122\n" +
	"\x06Public\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x04\x80\xb5\x18\x01\x127\n" +
	"\vAdminMethod\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x04\x88\xb5\x18\x01\x127\n" +
	"\vWriteMethod\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x04\x90\xb5\x18\x012G\n" +
	"\rPublicService\x120\n" +
	"\bDoPublic\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x00\x1a\x04\x80\xb5\x18\x012E\n" +
	"\fAdminService\x12/\n" +
	"\aDoAdmin\x12\x10.testproto.Empty\x1a\x10.testproto.Empty\"\x00\x1a\x04\x88\xb5\x18\x01B.Z,github.com/jesse0michael/pkg/grpc/proto/testb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_proto_goTypes = []any{
	(*Empty)(nil), // 0: testproto.Empty
}
var file_test_proto_depIdxs = []int32{
	0, // 0: testproto.TestService.Authed:input_type -> testproto.Empty
	0, // 1: testproto.TestService.Public:input_type -> testproto.Empty
	0, // 2: testproto.TestService.AdminMethod:input_type -> testproto.Empty
	0, // 3: testproto.TestService.WriteMethod:input_type -> testproto.Empty
	0, // 4: testproto.PublicService.DoPublic:input_type -> testproto.Empty
	0, // 5: testproto.AdminService.DoAdmin:input_type -> testproto.Empty
	0, // 6: testproto.TestService.Authed:output_type -> testproto.Empty
	0, // 7: testproto.TestService.Public:output_type -> testproto.Empty
	0, // 8: testproto.TestService.AdminMethod:output_type -> testproto.Empty
	0, // 9: testproto.TestService.WriteMethod:output_type -> testproto.Empty
	0, // 10: testproto.PublicService.DoPublic:output_type -> testproto.Empty
	0, // 11: testproto.AdminService.DoAdmin:output_type -> testproto.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
